"""Generate kb/roster.yaml: who is in which team, their role and capacity.

The training data has no real team membership (all 30 assignees appear in every
team), so we build a plausible, deterministic roster:
- every playbook resolver joins the team(s) owning the services they resolve;
- the remaining people are spread round-robin so each team has 2-4 members;
- the first non-resolver member of each team is its lead; one admin account.

    python -m app.scripts.build_roster /data/jira_first_20000_requested_fields_synthetic.json
"""

import json
import sys
from collections import defaultdict

import yaml

from app.config import settings
from app.domain import TEAMS, team_for


def _name(email: str) -> str:
    return " ".join(part.capitalize() for part in email.split("@")[0].split("."))


def build(training_path: str) -> list[dict]:
    tickets = json.load(open(training_path))
    assignees = sorted({t["Assignee"] for t in tickets if t.get("Assignee")})
    playbook = [json.loads(line) for line in (settings.kb_dir / "playbook.jsonl").read_text().splitlines() if line]

    teams_of: dict[str, list[str]] = defaultdict(list)
    for entry in playbook:
        team = team_for(entry["service"])
        if team not in teams_of[entry["resolver"]]:
            teams_of[entry["resolver"]].append(team)

    members: dict[str, list[str]] = defaultdict(list)
    for person, teams in teams_of.items():
        for team in teams:
            members[team].append(person)

    others = [p for p in assignees if p not in teams_of]
    for person in others:  # fill the smallest team first, ties in team order
        team = min(TEAMS, key=lambda t: (len(members[t]), TEAMS.index(t)))
        members[team].append(person)
        teams_of[person].append(team)

    leads = {team: next((p for p in people if p in others), people[0]) for team, people in members.items()}
    roster = [
        {
            "email": person,
            "name": _name(person),
            "role": "lead" if person in leads.values() else "analyst",
            "teams": teams_of[person],
            "capacity": settings.default_capacity,
        }
        for person in sorted(teams_of)
    ]
    roster.append({"email": "admin@intcom.com", "name": "Desk Admin", "role": "admin", "teams": [], "capacity": 0})
    return roster


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    roster = build(sys.argv[1])
    out = settings.kb_dir / "roster.yaml"
    out.write_text("# Generated by app/scripts/build_roster.py; edit freely.\n" + yaml.safe_dump(roster, sort_keys=False))
    print(f"Wrote {len(roster)} people to {out}")
