/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reference */
        get: operations["get_reference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Llm Models */
        get: operations["list_llm_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Priority */
        post: operations["compute_priority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets"];
        put?: never;
        /** Create Ticket */
        post: operations["create_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/from-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Email */
        post: operations["ingest_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Tickets */
        post: operations["import_tickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket"];
        put?: never;
        post?: never;
        /** Delete Ticket */
        delete: operations["delete_ticket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Triage Ticket */
        post: operations["triage_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Triage Batch */
        post: operations["triage_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Triage Result */
        get: operations["get_triage_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage/{result_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Triage */
        post: operations["review_triage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kb/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kb Documents */
        get: operations["list_kb_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Kb */
        post: operations["search_kb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kb/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Knowledge Base */
        post: operations["sync_knowledge_base"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Assistant */
        post: operations["ask_assistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Submission
         * @description Challenge-format records with our decisions filled in.
         *     Uses the analyst-approved/edited decision when there is one, else the latest AI proposal.
         *     TODO: confirm the exact expected submission format with Swiss Life.
         */
        get: operations["export_submission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssistantAnswer */
        AssistantAnswer: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Evidence"][];
            /** Model */
            model: string;
        };
        /** AssistantRequest */
        AssistantRequest: {
            /** Question */
            question: string;
            /**
             * Ticket Id
             * @description Ground the answer in this ticket as well
             */
            ticket_id?: string | null;
            /**
             * Model
             * @description LLM model from /api/llm/models; omit for the default, 'heuristic' for no LLM
             */
            model?: string | null;
        };
        /** BatchTriageRequest */
        BatchTriageRequest: {
            /**
             * Ticket Ids
             * @description Omit to triage every ticket in state 'new'
             */
            ticket_ids?: string[] | null;
            /** Source */
            source?: ("challenge" | "training" | "manual" | "email") | null;
            /**
             * Model
             * @description LLM model from /api/llm/models; omit for the default, 'heuristic' for no LLM
             */
            model?: string | null;
        };
        /** BatchTriageResult */
        BatchTriageResult: {
            /** Triaged */
            triaged: number;
            /** Failed */
            failed: number;
        };
        /** Body_import_tickets */
        Body_import_tickets: {
            /**
             * File
             * @description Jira export JSON (challenge or training format)
             */
            file: string;
            /**
             * Source
             * @default challenge
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email";
        };
        /**
         * Decision
         * @description The seven fields the challenge scores, plus Urgency/Impact.
         */
        Decision: {
            /**
             * Work Type
             * @enum {string}
             */
            work_type: "Incident" | "Service Request";
            /**
             * Service
             * @enum {string}
             */
            service: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /** Assignee */
            assignee: string | null;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "done" | "cancelled" | "clarification" | "cannot reproduce";
            /** Resolution Comment */
            resolution_comment: string;
        };
        /**
         * DecisionEdit
         * @description Analyst overrides. Team and priority are always recomputed server-side
         *     from service and urgency/impact, so they can never be inconsistent.
         */
        DecisionEdit: {
            /** Work Type */
            work_type?: ("Incident" | "Service Request") | null;
            /** Service */
            service?: ("Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets") | null;
            /** Assignee */
            assignee?: string | null;
            /** Urgency */
            urgency?: ("Highest" | "High" | "Medium" | "Low" | "Lowest") | null;
            /** Impact */
            impact?: ("Highest" | "High" | "Medium" | "Low" | "Lowest") | null;
            /** Resolution */
            resolution?: ("done" | "cancelled" | "clarification" | "cannot reproduce") | null;
            /** Resolution Comment */
            resolution_comment?: string | null;
        };
        /** EmailIngest */
        EmailIngest: {
            /** From Address */
            from_address: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Business Entity */
            business_entity?: string | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "service_card" | "playbook" | "historical_ticket";
            /** Ref Id */
            ref_id: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /**
             * Llm Provider
             * @enum {string}
             */
            llm_provider: "azure" | "openai" | "none";
            /** Llm Model */
            llm_model: string | null;
            /** Llm Configured */
            llm_configured: boolean;
            /** Embeddings Configured */
            embeddings_configured: boolean;
            /** Version */
            version: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
        };
        /** KbDocumentOut */
        KbDocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "service_card" | "playbook" | "historical_ticket";
            /** Ref Id */
            ref_id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Has Embedding */
            has_embedding: boolean;
        };
        /** KbSearchRequest */
        KbSearchRequest: {
            /** Query */
            query: string;
            /**
             * K
             * @default 5
             */
            k: number;
            /** Kinds */
            kinds?: ("service_card" | "playbook" | "historical_ticket")[] | null;
        };
        /** KbSyncResult */
        KbSyncResult: {
            /** Synced */
            synced: number;
            /** Embedded */
            embedded: number;
        };
        /** LlmModels */
        LlmModels: {
            /**
             * Provider
             * @description Main provider (Apertus is listed in `models` when configured)
             * @enum {string}
             */
            provider: "azure" | "openai" | "none";
            /** Default Model */
            default_model: string | null;
            /**
             * Models
             * @description Choices for the model picker ('heuristic' is always allowed too)
             */
            models: components["schemas"]["ModelOption"][];
        };
        /** Metrics */
        Metrics: {
            /** Tickets Total */
            tickets_total: number;
            /** By State */
            by_state: {
                [key: string]: number;
            };
            /** Reviews Total */
            reviews_total: number;
            /**
             * Acceptance Rate
             * @description approved / reviewed
             */
            acceptance_rate: number | null;
            /** Edit Rate */
            edit_rate: number | null;
            /** Reject Rate */
            reject_rate: number | null;
            /** Avg Review Seconds */
            avg_review_seconds: number | null;
            /** Avg Confidence */
            avg_confidence: number | null;
            /**
             * Field Override Counts
             * @description How often analysts changed each field
             */
            field_override_counts: {
                [key: string]: number;
            };
        };
        /** ModelOption */
        ModelOption: {
            /**
             * Id
             * @description Send this as `model` in triage/assistant requests
             */
            id: string;
            /** Label */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "azure" | "openai" | "apertus";
        };
        /** PriorityRequest */
        PriorityRequest: {
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
        };
        /** PriorityResponse */
        PriorityResponse: {
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
        };
        /**
         * ReferenceData
         * @description Everything the UI needs for dropdowns, labels and the priority matrix.
         */
        ReferenceData: {
            /** Services */
            services: components["schemas"]["ServiceInfo"][];
            /** Teams */
            teams: ("Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash")[];
            /** Levels */
            levels: ("Highest" | "High" | "Medium" | "Low" | "Lowest")[];
            /** Work Types */
            work_types: ("Incident" | "Service Request")[];
            /** Resolutions */
            resolutions: ("done" | "cancelled" | "clarification" | "cannot reproduce")[];
            /** Urgency Labels */
            urgency_labels: {
                [key: string]: string;
            };
            /** Impact Labels */
            impact_labels: {
                [key: string]: string;
            };
            /**
             * Priority Matrix
             * @description priority_matrix[urgency][impact] -> priority
             */
            priority_matrix: {
                [key: string]: {
                    [key: string]: "Highest" | "High" | "Medium" | "Low" | "Lowest";
                };
            };
        };
        /** ReviewCreate */
        ReviewCreate: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "edit" | "reject";
            edits?: components["schemas"]["DecisionEdit"] | null;
            /** Reviewer */
            reviewer: string;
            /** Notes */
            notes?: string | null;
            /**
             * Review Seconds
             * @description Time the analyst spent, measured by the UI
             */
            review_seconds?: number | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Triage Result Id
             * Format: uuid
             */
            triage_result_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "edit" | "reject";
            final: components["schemas"]["Decision"] | null;
            /** Overridden Fields */
            overridden_fields: string[];
            /** Reviewer */
            reviewer: string;
            /** Notes */
            notes: string | null;
            /** Review Seconds */
            review_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ServiceInfo */
        ServiceInfo: {
            /**
             * Name
             * @enum {string}
             */
            name: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /**
             * Criticality
             * @enum {string}
             */
            criticality: "Critical" | "Non-Critical";
        };
        /** TicketCreate */
        TicketCreate: {
            /** Work Type */
            work_type?: string | null;
            /** Request Type */
            request_type?: string | null;
            /** Summary */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Affected Service
             * @description Intake value; may be wrong
             */
            affected_service?: string | null;
            /** Business Entity */
            business_entity?: string | null;
            /** Reporter */
            reporter?: string | null;
            /** Urgency */
            urgency?: string | null;
            /** Impact */
            impact?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Status
             * @default open
             */
            status: string | null;
            /**
             * Linked Issues
             * @default []
             */
            linked_issues: string[];
            /**
             * Comments
             * @default []
             */
            comments: string[];
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email";
        };
        /** TicketDetail */
        TicketDetail: {
            /** Work Type */
            work_type?: string | null;
            /** Request Type */
            request_type?: string | null;
            /** Summary */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Affected Service
             * @description Intake value; may be wrong
             */
            affected_service?: string | null;
            /** Business Entity */
            business_entity?: string | null;
            /** Reporter */
            reporter?: string | null;
            /** Urgency */
            urgency?: string | null;
            /** Impact */
            impact?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Status
             * @default open
             */
            status: string | null;
            /**
             * Linked Issues
             * @default []
             */
            linked_issues: string[];
            /**
             * Comments
             * @default []
             */
            comments: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /**
             * Source
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email";
            /**
             * Triage State
             * @enum {string}
             */
            triage_state: "new" | "proposed" | "approved" | "edited" | "rejected";
            /** Source Created At */
            source_created_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            latest_triage: components["schemas"]["TriageResultOut"] | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
        };
        /** TicketOut */
        TicketOut: {
            /** Work Type */
            work_type?: string | null;
            /** Request Type */
            request_type?: string | null;
            /** Summary */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Affected Service
             * @description Intake value; may be wrong
             */
            affected_service?: string | null;
            /** Business Entity */
            business_entity?: string | null;
            /** Reporter */
            reporter?: string | null;
            /** Urgency */
            urgency?: string | null;
            /** Impact */
            impact?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Status
             * @default open
             */
            status: string | null;
            /**
             * Linked Issues
             * @default []
             */
            linked_issues: string[];
            /**
             * Comments
             * @default []
             */
            comments: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /**
             * Source
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email";
            /**
             * Triage State
             * @enum {string}
             */
            triage_state: "new" | "proposed" | "approved" | "edited" | "rejected";
            /** Source Created At */
            source_created_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TicketPage */
        TicketPage: {
            /** Items */
            items: components["schemas"]["TicketOut"][];
            /** Total */
            total: number;
        };
        /** TriageRequest */
        TriageRequest: {
            /**
             * Model
             * @description LLM model from /api/llm/models; omit for the default, 'heuristic' for no LLM
             */
            model?: string | null;
        };
        /** TriageResultOut */
        TriageResultOut: {
            /**
             * Work Type
             * @enum {string}
             */
            work_type: "Incident" | "Service Request";
            /**
             * Service
             * @enum {string}
             */
            service: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /** Assignee */
            assignee: string | null;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "done" | "cancelled" | "clarification" | "cannot reproduce";
            /** Resolution Comment */
            resolution_comment: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Changed Fields
             * @description Fields that differ from the intake values
             */
            changed_fields: string[];
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_reference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceData"];
                };
            };
        };
    };
    list_llm_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmModels"];
                };
            };
        };
    };
    compute_priority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets: {
        parameters: {
            query?: {
                state?: ("new" | "proposed" | "approved" | "edited" | "rejected") | null;
                source?: ("challenge" | "training" | "manual" | "email") | null;
                /** @description Search summary and description */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIngest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_tickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_tickets"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    triage_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TriageRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    triage_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTriageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchTriageResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_triage_result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_triage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kb_documents: {
        parameters: {
            query?: {
                kind?: ("service_card" | "playbook" | "historical_ticket") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_kb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KbSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_knowledge_base: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbSyncResult"];
                };
            };
        };
    };
    ask_assistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
        };
    };
    export_submission: {
        parameters: {
            query?: {
                source?: "challenge" | "training" | "manual" | "email";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
