/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reference */
        get: operations["get_reference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Llm Models */
        get: operations["list_llm_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Priority */
        post: operations["compute_priority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubric/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Rubric
         * @description What impact/urgency/priority would these facts produce? (live preview while editing)
         */
        post: operations["preview_rubric"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings View */
        get: operations["get_settings_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets"];
        put?: never;
        /** Create Ticket */
        post: operations["create_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/from-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Email */
        post: operations["ingest_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Tickets */
        post: operations["import_tickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket"];
        put?: never;
        post?: never;
        /** Delete Ticket */
        delete: operations["delete_ticket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Ticket */
        post: operations["assign_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Triage Ticket */
        post: operations["triage_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/triage/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Triage
         * @description Live walkthrough: runs the pipeline and streams each stage as it happens.
         */
        get: operations["stream_triage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Triage Batch */
        post: operations["triage_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Triage Result */
        get: operations["get_triage_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage/{result_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Triage */
        post: operations["review_triage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kb/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kb Documents */
        get: operations["list_kb_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Kb */
        post: operations["search_kb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kb/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Knowledge Base */
        post: operations["sync_knowledge_base"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Assistant */
        post: operations["ask_assistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Copilot
         * @description Copilot chat: retrieves knowledge for the latest question, then streams the answer token by token.
         */
        post: operations["stream_copilot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calibration
         * @description Does confidence mean something? Per confidence bucket, the share of reviewed proposals
         *     that analysts accepted without changing service or priority.
         */
        get: operations["get_calibration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Submission
         * @description Challenge-format records with our decisions filled in.
         *     Uses the analyst-approved/edited decision when there is one, else the latest AI proposal.
         *     TODO: confirm the exact expected submission format with Swiss Life.
         */
        get: operations["export_submission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Impact
         * @description Business view: the service-desk pain points and how much of each the system handled.
         */
        get: operations["get_impact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workload */
        get: operations["get_workload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages"];
        put?: never;
        /** Send Message */
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Message
         * @description AI-drafted escalation / hand-off / question about a ticket, addressed to a person or a team.
         */
        post: operations["draft_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Directory */
        get: operations["get_directory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignRequest */
        AssignRequest: {
            /** Assignee */
            assignee: string;
        };
        /** AssigneeCandidate */
        AssigneeCandidate: {
            /** User */
            user: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Open */
            open: number;
            /** Capacity */
            capacity: number;
            /** Expertise */
            expertise: number;
        };
        /** AssigneeSuggestion */
        AssigneeSuggestion: {
            /**
             * Expert
             * @description Resolver of the matched playbook entry (used for the export)
             */
            expert: string | null;
            /**
             * Recommended
             * @description Best candidate after workload balancing
             */
            recommended: string | null;
            /** Reason */
            reason: string;
            /** Candidates */
            candidates: components["schemas"]["AssigneeCandidate"][];
        };
        /** AssistantAnswer */
        AssistantAnswer: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Evidence"][];
            /** Model */
            model: string;
        };
        /** AssistantRequest */
        AssistantRequest: {
            /** Question */
            question: string;
            /**
             * Ticket Id
             * @description Ground the answer in this ticket as well
             */
            ticket_id?: string | null;
            /**
             * Model
             * @description LLM model from /api/llm/models; omit for the default, 'heuristic' for no LLM
             */
            model?: string | null;
        };
        /** BatchTriageRequest */
        BatchTriageRequest: {
            /**
             * Ticket Ids
             * @description Omit to triage every ticket in state 'new'
             */
            ticket_ids?: string[] | null;
            /** Source */
            source?: ("challenge" | "training" | "manual" | "email" | "demo") | null;
            /**
             * Model
             * @description LLM model from /api/llm/models; omit for the default, 'heuristic' for no LLM
             */
            model?: string | null;
        };
        /** BatchTriageResult */
        BatchTriageResult: {
            /** Triaged */
            triaged: number;
            /** Failed */
            failed: number;
        };
        /** Body_import_tickets */
        Body_import_tickets: {
            /**
             * File
             * @description Jira export JSON (challenge or training format)
             */
            file: string;
            /**
             * Source
             * @default challenge
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email" | "demo";
        };
        /** Calibration */
        Calibration: {
            /** Buckets */
            buckets: components["schemas"]["CalibrationBucket"][];
            /** Note */
            note: string;
        };
        /** CalibrationBucket */
        CalibrationBucket: {
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Reviewed */
            reviewed: number;
            /**
             * Agreement
             * @description Share approved without changing service or priority
             */
            agreement: number | null;
        };
        /** ChannelOut */
        ChannelOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team" | "dm";
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Members */
            members: string[];
            last_message: components["schemas"]["MessageOut"] | null;
            /** Message Count */
            message_count: number;
        };
        /** ChatTurn */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ConfidenceOut */
        ConfidenceOut: {
            /**
             * Overall
             * @description min(votes, retrieval) x flag multipliers
             */
            overall: number;
            /**
             * Votes
             * @description How consistently the model answered across votes
             */
            votes: number;
            /**
             * Retrieval
             * @description How closely the matched past solution fits
             */
            retrieval: number;
            /**
             * Flags
             * @description Reasons for caution, e.g. generic_service, unclear_input
             */
            flags: string[];
        };
        /**
         * CopilotEvent
         * @description Server-sent event of POST /api/assistant/stream: sources first, then tokens, then done.
         */
        CopilotEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "sources" | "token" | "done" | "error";
            /** Text */
            text?: string | null;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["Evidence"][];
            /** Model */
            model?: string | null;
        };
        /** CopilotRequest */
        CopilotRequest: {
            /**
             * Messages
             * @description Conversation so far; the last one is the question
             */
            messages: components["schemas"]["ChatTurn"][];
            /** Ticket Id */
            ticket_id?: string | null;
            /** Model */
            model?: string | null;
        };
        /** DailyPoint */
        DailyPoint: {
            /** Day */
            day: string;
            /** Created */
            created: number;
            /** Triaged */
            triaged: number;
            /** Approved */
            approved: number;
            /** Edited */
            edited: number;
            /** Rejected */
            rejected: number;
            /** Auto */
            auto: number;
            /** Review */
            review: number;
            /** Triage */
            triage: number;
            /**
             * Misroutes
             * @description Proposals whose service differs from the intake service
             */
            misroutes: number;
            /** Avg Review Seconds */
            avg_review_seconds: number | null;
            /** Acceptance Rate */
            acceptance_rate: number | null;
        };
        /**
         * Decision
         * @description The seven fields the challenge scores, plus Urgency/Impact.
         */
        Decision: {
            /**
             * Work Type
             * @enum {string}
             */
            work_type: "Incident" | "Service Request";
            /**
             * Service
             * @enum {string}
             */
            service: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /** Assignee */
            assignee: string | null;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "done" | "cancelled" | "clarification" | "cannot reproduce";
            /** Resolution Comment */
            resolution_comment: string;
        };
        /**
         * DecisionEdit
         * @description Analyst overrides. Team and priority are always recomputed server-side
         *     from service and urgency/impact, so they can never be inconsistent.
         */
        DecisionEdit: {
            /** Work Type */
            work_type?: ("Incident" | "Service Request") | null;
            /** Service */
            service?: ("Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets") | null;
            /** Assignee */
            assignee?: string | null;
            /** Urgency */
            urgency?: ("Highest" | "High" | "Medium" | "Low" | "Lowest") | null;
            /** Impact */
            impact?: ("Highest" | "High" | "Medium" | "Low" | "Lowest") | null;
            /** Resolution */
            resolution?: ("done" | "cancelled" | "clarification" | "cannot reproduce") | null;
            /** Resolution Comment */
            resolution_comment?: string | null;
        };
        /** Department */
        Department: {
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /** Channel */
            channel: string;
            /** Services */
            services: components["schemas"]["ServiceBrief"][];
            lead: components["schemas"]["MemberBrief"] | null;
            /** Members */
            members: components["schemas"]["MemberBrief"][];
            /** Open Tickets */
            open_tickets: number;
            /** Escalations */
            escalations: number;
            /** Messages 7D */
            messages_7d: number;
        };
        /** DraftOut */
        DraftOut: {
            /** Channel */
            channel: string;
            /** Recipient Label */
            recipient_label: string;
            /** Body */
            body: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "message" | "system" | "escalation" | "handoff";
            /** Model */
            model: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /** Sender */
            sender: string;
            /**
             * To
             * @description A person's email, or 'team:<Team>'
             */
            to: string;
            /**
             * Purpose
             * @default escalate
             * @enum {string}
             */
            purpose: "escalate" | "handoff" | "question";
            /** Model */
            model?: string | null;
        };
        /** EmailIngest */
        EmailIngest: {
            /** From Address */
            from_address: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Business Entity */
            business_entity?: string | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "service_card" | "playbook" | "historical_ticket";
            /** Ref Id */
            ref_id: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
        };
        /** Facts */
        Facts: {
            /**
             * Scope
             * @description Who is affected: one person up to external counterparties
             * @enum {string}
             */
            scope: "individual" | "team" | "one_entity" | "multi_entity" | "external_counterparty";
            /**
             * Outage Extent
             * @enum {string}
             */
            outage_extent: "none" | "partial_degradation" | "full_unavailability";
            /**
             * Workaround
             * @enum {string}
             */
            workaround: "none" | "difficult" | "easy" | "not_applicable";
            /**
             * Regulatory Or Security
             * @description Actual regulatory breach or security compromise
             */
            regulatory_or_security: boolean;
            /**
             * Deadline Pressure
             * @enum {string}
             */
            deadline_pressure: "none" | "soft" | "hard";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /**
             * Llm Provider
             * @enum {string}
             */
            llm_provider: "azure" | "openai" | "none";
            /** Llm Model */
            llm_model: string | null;
            /** Llm Configured */
            llm_configured: boolean;
            /** Embeddings Configured */
            embeddings_configured: boolean;
            /** Version */
            version: string;
        };
        /** Impact */
        Impact: {
            /** Include Demo */
            include_demo: boolean;
            /** Tickets */
            tickets: number;
            /** Tickets Triaged */
            tickets_triaged: number;
            /** Misroutes Caught */
            misroutes_caught: number;
            /** Priority Corrected */
            priority_corrected: number;
            /** Clarifications Requested */
            clarifications_requested: number;
            /** Escalations */
            escalations: number;
            /** Auto Routed Share */
            auto_routed_share: number | null;
            /** Acceptance Rate */
            acceptance_rate: number | null;
            /** Avg Triage Seconds */
            avg_triage_seconds: number | null;
            /** Avg Review Seconds */
            avg_review_seconds: number | null;
            /** Minutes Saved */
            minutes_saved: number;
            /** Manual Triage Minutes */
            manual_triage_minutes: number;
            /**
             * Max Load
             * @description Busiest person's open tickets divided by their capacity
             */
            max_load: number | null;
            /**
             * Over Capacity
             * @description People at or over capacity
             */
            over_capacity: number;
            /** Learned Documents */
            learned_documents: number;
            /** Days */
            days: components["schemas"]["DailyPoint"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
        };
        /** KbDocumentOut */
        KbDocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "service_card" | "playbook" | "historical_ticket";
            /** Ref Id */
            ref_id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Has Embedding */
            has_embedding: boolean;
        };
        /** KbSearchRequest */
        KbSearchRequest: {
            /** Query */
            query: string;
            /**
             * K
             * @default 5
             */
            k: number;
            /** Kinds */
            kinds?: ("service_card" | "playbook" | "historical_ticket")[] | null;
        };
        /** KbSyncResult */
        KbSyncResult: {
            /** Synced */
            synced: number;
            /** Embedded */
            embedded: number;
        };
        /** LlmModels */
        LlmModels: {
            /**
             * Provider
             * @description Main provider (Apertus is listed in `models` when configured)
             * @enum {string}
             */
            provider: "azure" | "openai" | "none";
            /** Default Model */
            default_model: string | null;
            /**
             * Models
             * @description Choices for the model picker ('heuristic' is always allowed too)
             */
            models: components["schemas"]["ModelOption"][];
        };
        /**
         * ManualFields
         * @description Values staff fill in themselves. The pipeline keeps them and only fills the gaps.
         */
        ManualFields: {
            /** Work Type */
            work_type?: ("Incident" | "Service Request") | null;
            /** Service */
            service?: ("Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets") | null;
            /** Urgency */
            urgency?: ("Highest" | "High" | "Medium" | "Low" | "Lowest") | null;
            /** Impact */
            impact?: ("Highest" | "High" | "Medium" | "Low" | "Lowest") | null;
            /** Assignee */
            assignee?: string | null;
            /** Resolution */
            resolution?: ("done" | "cancelled" | "clarification" | "cannot reproduce") | null;
            /** Resolution Comment */
            resolution_comment?: string | null;
        };
        /** MemberBrief */
        MemberBrief: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "analyst" | "lead" | "admin";
            /** Open */
            open: number;
            /** Capacity */
            capacity: number;
        };
        /** MessageCreate */
        MessageCreate: {
            /**
             * Channel
             * @description "team:<Team>" or "dm:<email>|<email>" (any order)
             */
            channel: string;
            /** Sender */
            sender: string;
            /** Body */
            body: string;
            /**
             * Kind
             * @default message
             * @enum {string}
             */
            kind: "message" | "system" | "escalation" | "handoff";
            /**
             * Ticket Id
             * @description Attach a ticket; kind 'escalation' also marks it escalated
             */
            ticket_id?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel */
            channel: string;
            /** Sender */
            sender: string;
            /** Sender Name */
            sender_name: string;
            /** Body */
            body: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "message" | "system" | "escalation" | "handoff";
            /** Ticket Id */
            ticket_id: string | null;
            /** Ticket Number */
            ticket_number?: number | null;
            /** Ticket Summary */
            ticket_summary?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Metrics */
        Metrics: {
            /** Tickets Total */
            tickets_total: number;
            /** By State */
            by_state: {
                [key: string]: number;
            };
            /** Reviews Total */
            reviews_total: number;
            /**
             * Acceptance Rate
             * @description approved / reviewed
             */
            acceptance_rate: number | null;
            /** Edit Rate */
            edit_rate: number | null;
            /** Reject Rate */
            reject_rate: number | null;
            /** Avg Review Seconds */
            avg_review_seconds: number | null;
            /** Avg Confidence */
            avg_confidence: number | null;
            /**
             * Field Override Counts
             * @description How often analysts changed each field
             */
            field_override_counts: {
                [key: string]: number;
            };
            /**
             * By Route
             * @description Latest proposals per route (auto/review/triage)
             */
            by_route: {
                [key: string]: number;
            };
            /** Escalations Open */
            escalations_open: number;
            /**
             * Sla Breaches
             * @description Open tickets past their SLA deadline
             */
            sla_breaches: number;
            /**
             * Priority Intake
             * @description Priority as submitted
             */
            priority_intake: {
                [key: string]: number;
            };
            /**
             * Priority Ai
             * @description Priority after triage
             */
            priority_ai: {
                [key: string]: number;
            };
        };
        /** ModelOption */
        ModelOption: {
            /**
             * Id
             * @description Send this as `model` in triage/assistant requests
             */
            id: string;
            /** Label */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "azure" | "openai" | "apertus";
        };
        /** PriorityRequest */
        PriorityRequest: {
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
        };
        /** PriorityResponse */
        PriorityResponse: {
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
        };
        /**
         * ReferenceData
         * @description Everything the UI needs for dropdowns, labels and the priority matrix.
         */
        ReferenceData: {
            /** Services */
            services: components["schemas"]["ServiceInfo"][];
            /** Teams */
            teams: ("Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash")[];
            /** Levels */
            levels: ("Highest" | "High" | "Medium" | "Low" | "Lowest")[];
            /** Work Types */
            work_types: ("Incident" | "Service Request")[];
            /** Resolutions */
            resolutions: ("done" | "cancelled" | "clarification" | "cannot reproduce")[];
            /** Urgency Labels */
            urgency_labels: {
                [key: string]: string;
            };
            /** Impact Labels */
            impact_labels: {
                [key: string]: string;
            };
            /**
             * Priority Matrix
             * @description priority_matrix[urgency][impact] -> priority
             */
            priority_matrix: {
                [key: string]: {
                    [key: string]: "Highest" | "High" | "Medium" | "Low" | "Lowest";
                };
            };
        };
        /** ReviewCreate */
        ReviewCreate: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "edit" | "reject";
            edits?: components["schemas"]["DecisionEdit"] | null;
            /** Reviewer */
            reviewer: string;
            /** Notes */
            notes?: string | null;
            /**
             * Review Seconds
             * @description Time the analyst spent, measured by the UI
             */
            review_seconds?: number | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Triage Result Id
             * Format: uuid
             */
            triage_result_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "edit" | "reject";
            final: components["schemas"]["Decision"] | null;
            /** Overridden Fields */
            overridden_fields: string[];
            /** Reviewer */
            reviewer: string;
            /** Notes */
            notes: string | null;
            /** Review Seconds */
            review_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RubricPreview */
        RubricPreview: {
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /** Priority Score */
            priority_score: number;
            /** Rubric Trace */
            rubric_trace: string[];
        };
        /** RubricPreviewRequest */
        RubricPreviewRequest: {
            facts: components["schemas"]["Facts"];
            /**
             * Service
             * @enum {string}
             */
            service: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Work Type
             * @enum {string}
             */
            work_type: "Incident" | "Service Request";
        };
        /** ServiceBrief */
        ServiceBrief: {
            /**
             * Name
             * @enum {string}
             */
            name: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Criticality
             * @enum {string}
             */
            criticality: "Critical" | "Non-Critical";
        };
        /** ServiceInfo */
        ServiceInfo: {
            /**
             * Name
             * @enum {string}
             */
            name: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /**
             * Criticality
             * @enum {string}
             */
            criticality: "Critical" | "Non-Critical";
        };
        /** SettingsOut */
        SettingsOut: {
            /** Auto Threshold */
            auto_threshold: number;
            /** Triage Threshold */
            triage_threshold: number;
            /** Sla Hours */
            sla_hours: {
                [key: string]: number;
            };
            /** Votes */
            votes: number;
            /** Max Share */
            max_share: number;
            /** Default Capacity */
            default_capacity: number;
        };
        /**
         * TicketCreate
         * @description New-ticket form: summary, description and reporter are required; anything in `manual`
         *     is confirmed by staff, everything else is derived by the pipeline.
         */
        TicketCreate: {
            /** Work Type */
            work_type?: string | null;
            /** Request Type */
            request_type?: string | null;
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Affected Service
             * @description Intake value; may be wrong
             */
            affected_service?: string | null;
            /** Business Entity */
            business_entity?: string | null;
            /** Reporter */
            reporter?: string | null;
            /** Urgency */
            urgency?: string | null;
            /** Impact */
            impact?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Status
             * @default open
             */
            status: string | null;
            /**
             * Linked Issues
             * @default []
             */
            linked_issues: string[];
            /**
             * Comments
             * @default []
             */
            comments: string[];
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email" | "demo";
            manual?: components["schemas"]["ManualFields"] | null;
        };
        /** TicketDetail */
        TicketDetail: {
            /** Work Type */
            work_type?: string | null;
            /** Request Type */
            request_type?: string | null;
            /** Summary */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Affected Service
             * @description Intake value; may be wrong
             */
            affected_service?: string | null;
            /** Business Entity */
            business_entity?: string | null;
            /** Reporter */
            reporter?: string | null;
            /** Urgency */
            urgency?: string | null;
            /** Impact */
            impact?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Status
             * @default open
             */
            status: string | null;
            /**
             * Linked Issues
             * @default []
             */
            linked_issues: string[];
            /**
             * Comments
             * @default []
             */
            comments: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /**
             * Source
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email" | "demo";
            /**
             * Triage State
             * @enum {string}
             */
            triage_state: "new" | "proposed" | "approved" | "edited" | "rejected";
            /** Source Created At */
            source_created_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Assignee */
            assignee?: string | null;
            /** Ai Service */
            ai_service?: string | null;
            /** Ai Team */
            ai_team?: string | null;
            /** Ai Priority */
            ai_priority?: string | null;
            /** Priority Score */
            priority_score?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Route */
            route?: ("auto" | "review" | "triage") | null;
            /**
             * Escalated
             * @default false
             */
            escalated: boolean;
            /** Sla Due At */
            sla_due_at?: string | null;
            /**
             * Manual Fields
             * @description Fields confirmed by staff at creation
             * @default []
             */
            manual_fields: string[];
            latest_triage: components["schemas"]["TriageResultOut"] | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
        };
        /** TicketOut */
        TicketOut: {
            /** Work Type */
            work_type?: string | null;
            /** Request Type */
            request_type?: string | null;
            /** Summary */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Affected Service
             * @description Intake value; may be wrong
             */
            affected_service?: string | null;
            /** Business Entity */
            business_entity?: string | null;
            /** Reporter */
            reporter?: string | null;
            /** Urgency */
            urgency?: string | null;
            /** Impact */
            impact?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Status
             * @default open
             */
            status: string | null;
            /**
             * Linked Issues
             * @default []
             */
            linked_issues: string[];
            /**
             * Comments
             * @default []
             */
            comments: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /**
             * Source
             * @enum {string}
             */
            source: "challenge" | "training" | "manual" | "email" | "demo";
            /**
             * Triage State
             * @enum {string}
             */
            triage_state: "new" | "proposed" | "approved" | "edited" | "rejected";
            /** Source Created At */
            source_created_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Assignee */
            assignee?: string | null;
            /** Ai Service */
            ai_service?: string | null;
            /** Ai Team */
            ai_team?: string | null;
            /** Ai Priority */
            ai_priority?: string | null;
            /** Priority Score */
            priority_score?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Route */
            route?: ("auto" | "review" | "triage") | null;
            /**
             * Escalated
             * @default false
             */
            escalated: boolean;
            /** Sla Due At */
            sla_due_at?: string | null;
            /**
             * Manual Fields
             * @description Fields confirmed by staff at creation
             * @default []
             */
            manual_fields: string[];
        };
        /** TicketPage */
        TicketPage: {
            /** Items */
            items: components["schemas"]["TicketOut"][];
            /** Total */
            total: number;
        };
        /** TriageRequest */
        TriageRequest: {
            /**
             * Model
             * @description LLM model from /api/llm/models; omit for the default, 'heuristic' for no LLM
             */
            model?: string | null;
        };
        /** TriageResultOut */
        TriageResultOut: {
            /**
             * Work Type
             * @enum {string}
             */
            work_type: "Incident" | "Service Request";
            /**
             * Service
             * @enum {string}
             */
            service: "Trading Platform" | "Order Management" | "Trade Matching" | "Securities Settlement" | "Corporate Actions" | "Fund Pricing" | "NAV Calculation" | "Portfolio Accounting" | "Cash Management" | "Risk & Compliance Monitoring" | "Regulatory Reporting" | "SimCorp Dimension" | "Rimes Data Feed" | "Client Reporting" | "Tax Reporting" | "CRM & Client Portal" | "Identity & Access Management" | "SharePoint & File Storage" | "Outlook & Email" | "Emailed Support Tickets";
            /**
             * Team
             * @enum {string}
             */
            team: "Service Desk" | "Enterprise Applications" | "Investment Operations" | "Securities Operations" | "Risk & Controls" | "Valuation & Pricing" | "Client Services" | "Market Data Services" | "Trading Support" | "Tax & Reporting" | "Treasury & Cash";
            /** Assignee */
            assignee: string | null;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Impact
             * @enum {string}
             */
            impact: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Priority
             * @enum {string}
             */
            priority: "Highest" | "High" | "Medium" | "Low" | "Lowest";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "done" | "cancelled" | "clarification" | "cannot reproduce";
            /** Resolution Comment */
            resolution_comment: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Confidence
             * @description Overall confidence (same as confidence_detail.overall)
             */
            confidence: number;
            confidence_detail?: components["schemas"]["ConfidenceOut"] | null;
            facts?: components["schemas"]["Facts"] | null;
            /** Priority Score */
            priority_score?: number | null;
            /**
             * Rubric Trace
             * @default []
             */
            rubric_trace: string[];
            /**
             * Vote Agreement
             * @default {}
             */
            vote_agreement: {
                [key: string]: number;
            };
            /** Route */
            route?: ("auto" | "review" | "triage") | null;
            /**
             * Escalated
             * @default false
             */
            escalated: boolean;
            /** Sla Due At */
            sla_due_at?: string | null;
            assignee_suggestion?: components["schemas"]["AssigneeSuggestion"] | null;
            /** Playbook Ref */
            playbook_ref?: string | null;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Changed Fields
             * @description Fields that differ from the intake values
             */
            changed_fields: string[];
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TriageStreamEvent
         * @description One step of the live triage walkthrough (GET /api/tickets/{id}/triage/stream, server-sent events).
         *
         *     `data` per stage: retrieve -> {evidence, hybrid} · vote -> {index, ok, answer, error} ·
         *     extract -> {extraction, vote_agreement, votes_score, heuristic, manual} ·
         *     rubric -> {facts, impact, urgency, priority, priority_score, trace, critical} ·
         *     confidence -> {confidence, route, escalated, sla_due_at} · assign -> {suggestion, working_assignee} ·
         *     draft -> {comment, reference} · done -> {triage_result_id} · error -> {detail}
         */
        TriageStreamEvent: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "retrieve" | "extract" | "vote" | "rubric" | "confidence" | "assign" | "draft" | "done" | "error";
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "completed" | "failed";
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Message */
            message: string;
            /**
             * Data
             * @default {}
             */
            data: {
                [key: string]: unknown;
            };
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "analyst" | "lead" | "admin";
            /** Teams */
            teams: string[];
            /** Capacity */
            capacity: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workload */
        Workload: {
            /** Team */
            team: string;
            /** Open Total */
            open_total: number;
            /** Members */
            members: components["schemas"]["WorkloadMember"][];
            /** Escalations */
            escalations: components["schemas"]["TicketOut"][];
        };
        /** WorkloadMember */
        WorkloadMember: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "analyst" | "lead" | "admin";
            /** Open */
            open: number;
            /** Capacity */
            capacity: number;
            /**
             * Share
             * @description Share of the team's open tickets
             */
            share: number;
            /**
             * High Open
             * @description Open tickets with priority High or Highest
             */
            high_open: number;
            /** Oldest Open At */
            oldest_open_at: string | null;
            /** Approved 7D */
            approved_7d: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_reference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceData"];
                };
            };
        };
    };
    list_llm_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmModels"];
                };
            };
        };
    };
    compute_priority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_rubric: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    list_tickets: {
        parameters: {
            query?: {
                /** @description Queue tab */
                view?: "mine" | "team" | "needs_review" | "escalations" | "all";
                /** @description Email of the person viewing (for 'mine' / 'team') */
                as_user?: string | null;
                sort?: string;
                state?: ("new" | "proposed" | "approved" | "edited" | "rejected") | null;
                source?: ("challenge" | "training" | "manual" | "email" | "demo") | null;
                /** @description AI service */
                service?: string | null;
                /** @description AI team */
                team?: string | null;
                /** @description Search summary and description */
                q?: string | null;
                /** @description Also list closed tickets (status done) */
                include_closed?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIngest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_tickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_tickets"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    triage_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TriageRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_triage: {
        parameters: {
            query?: {
                /** @description Model from /api/llm/models, or 'heuristic' */
                model?: string | null;
            };
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events, one TriageStreamEvent per stage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                    "application/json": components["schemas"]["TriageStreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    triage_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTriageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchTriageResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_triage_result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_triage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kb_documents: {
        parameters: {
            query?: {
                kind?: ("service_card" | "playbook" | "historical_ticket") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_kb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KbSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_knowledge_base: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbSyncResult"];
                };
            };
        };
    };
    ask_assistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_copilot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotRequest"];
            };
        };
        responses: {
            /** @description Server-sent events: one 'sources', many 'token', then 'done' */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                    "application/json": components["schemas"]["CopilotEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
        };
    };
    get_calibration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calibration"];
                };
            };
        };
    };
    export_submission: {
        parameters: {
            query?: {
                source?: "challenge" | "training" | "manual" | "email" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_impact: {
        parameters: {
            query?: {
                include_demo?: boolean;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Impact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                team?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workload: {
        parameters: {
            query: {
                /** @description Team name, e.g. 'Client Services' */
                team: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels: {
        parameters: {
            query: {
                /** @description Email of the person viewing */
                as_user: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages: {
        parameters: {
            query: {
                channel: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
        };
    };
}
