// Friendly names for the generated contract types. Import from here in components.
import type { components, paths } from './schema'

type Schemas = components['schemas']

export type Ticket = Schemas['TicketOut']
export type TicketDetail = Schemas['TicketDetail']
export type TicketPage = Schemas['TicketPage']
export type TicketCreate = Schemas['TicketCreate']
export type EmailIngest = Schemas['EmailIngest']
export type TriageResult = Schemas['TriageResultOut']
export type Decision = Schemas['Decision']
export type DecisionEdit = Schemas['DecisionEdit']
export type ReviewCreate = Schemas['ReviewCreate']
export type Review = Schemas['ReviewOut']
export type Evidence = Schemas['Evidence']
export type KbDocument = Schemas['KbDocumentOut']
export type KbSearchRequest = Schemas['KbSearchRequest']
export type AssistantRequest = Schemas['AssistantRequest']
export type AssistantAnswer = Schemas['AssistantAnswer']
export type Metrics = Schemas['Metrics']
export type ReferenceData = Schemas['ReferenceData']
export type Health = Schemas['Health']
export type LlmModels = Schemas['LlmModels']
export type TriageRequest = Schemas['TriageRequest']
export type BatchTriageRequest = Schemas['BatchTriageRequest']
export type Facts = Schemas['Facts']
export type ConfidenceDetail = Schemas['ConfidenceOut']
export type AssigneeSuggestion = Schemas['AssigneeSuggestion']
export type User = Schemas['UserOut']
export type Workload = Schemas['Workload']
export type Calibration = Schemas['Calibration']
export type Settings = Schemas['SettingsOut']
export type RubricPreviewRequest = Schemas['RubricPreviewRequest']
export type Message = Schemas['MessageOut']
export type MessageCreate = Schemas['MessageCreate']
export type Channel = Schemas['ChannelOut']
export type DraftRequest = Schemas['DraftRequest']
export type Draft = Schemas['DraftOut']
export type Department = Schemas['Department']
export type Member = Schemas['MemberBrief']
export type Impact = Schemas['Impact']
export type DailyPoint = Schemas['DailyPoint']
export type ChatTurn = Schemas['ChatTurn']
export type CopilotEvent = Schemas['CopilotEvent']

export type Level = Schemas['PriorityResponse']['priority']
export type ServiceName = Decision['service']
export type TriageState = Ticket['triage_state']
export type TicketSource = Ticket['source']
export type EvidenceKind = Evidence['kind']
export type Route = NonNullable<Ticket['route']>
export type Role = User['role']
export type TicketView = NonNullable<TicketListParams['view']>

export type TicketListParams = NonNullable<paths['/api/tickets']['get']['parameters']['query']>
