"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 13:43:56.239952
"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id')
    )
    op.create_index(op.f('ix_kb_documents_kind'), 'kb_documents', ['kind'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('number', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('work_type', sa.String(length=40), nullable=True),
    sa.Column('request_type', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('affected_service', sa.String(length=80), nullable=True),
    sa.Column('business_entity', sa.String(length=40), nullable=True),
    sa.Column('reporter', sa.String(length=120), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('linked_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('triage_state', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_tickets_source'), 'tickets', ['source'], unique=False)
    op.create_index(op.f('ix_tickets_triage_state'), 'tickets', ['triage_state'], unique=False)
    op.create_table('triage_results',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('work_type', sa.String(length=40), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('team', sa.String(length=80), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=False),
    sa.Column('resolution_comment', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), server_default='', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_results_ticket_id'), 'triage_results', ['ticket_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('triage_result_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('final', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overridden_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_result_id'], ['triage_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_ticket_id'), 'reviews', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_ticket_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_triage_results_ticket_id'), table_name='triage_results')
    op.drop_table('triage_results')
    op.drop_index(op.f('ix_tickets_triage_state'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_kb_documents_kind'), table_name='kb_documents')
    op.drop_table('kb_documents')
    # ### end Alembic commands ###
