"""messaging

Revision ID: 0003_messaging
Revises: 0002
Create Date: 2026-09-25 02:00:41.048629
"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = '0003_messaging'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent: the shared Supabase may already have some of these (e.g. tickets.assignee).
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel', sa.String(length=300), nullable=False),
    sa.Column('sender', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='message', nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_messages_channel'), 'messages', ['channel'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_messages_ticket_id'), 'messages', ['ticket_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_ticket_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
