"""triage copilot

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 00:35:02.417171
"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent: the shared Supabase may already have some of these (e.g. tickets.assignee).
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=10), server_default='analyst', nullable=False),
    sa.Column('teams', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='8', nullable=False),
    sa.PrimaryKeyConstraint('email'),
    if_not_exists=True,
    )
    op.add_column('tickets', sa.Column('assignee', sa.String(length=120), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('ai_service', sa.String(length=80), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('ai_team', sa.String(length=80), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('ai_priority', sa.String(length=10), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('priority_score', sa.Float(), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('confidence', sa.Float(), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('route', sa.String(length=10), nullable=True), if_not_exists=True)
    op.add_column('tickets', sa.Column('escalated', sa.Boolean(), server_default=sa.text('false'), nullable=False), if_not_exists=True)
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True), if_not_exists=True)
    op.create_index(op.f('ix_tickets_ai_team'), 'tickets', ['ai_team'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_tickets_assignee'), 'tickets', ['assignee'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_tickets_priority_score'), 'tickets', ['priority_score'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_tickets_route'), 'tickets', ['route'], unique=False, if_not_exists=True)
    op.add_column('triage_results', sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True), if_not_exists=True)
    op.add_column('triage_results', sa.Column('priority_score', sa.Float(), nullable=True), if_not_exists=True)
    op.add_column('triage_results', sa.Column('rubric_trace', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False), if_not_exists=True)
    op.add_column('triage_results', sa.Column('vote_agreement', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), if_not_exists=True)
    op.add_column('triage_results', sa.Column('confidence_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True), if_not_exists=True)
    op.add_column('triage_results', sa.Column('route', sa.String(length=10), nullable=True), if_not_exists=True)
    op.add_column('triage_results', sa.Column('escalated', sa.Boolean(), server_default=sa.text('false'), nullable=False), if_not_exists=True)
    op.add_column('triage_results', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True), if_not_exists=True)
    op.add_column('triage_results', sa.Column('assignee_suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True), if_not_exists=True)
    op.add_column('triage_results', sa.Column('playbook_ref', sa.String(length=120), nullable=True), if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_results', 'playbook_ref')
    op.drop_column('triage_results', 'assignee_suggestion')
    op.drop_column('triage_results', 'sla_due_at')
    op.drop_column('triage_results', 'escalated')
    op.drop_column('triage_results', 'route')
    op.drop_column('triage_results', 'confidence_detail')
    op.drop_column('triage_results', 'vote_agreement')
    op.drop_column('triage_results', 'rubric_trace')
    op.drop_column('triage_results', 'priority_score')
    op.drop_column('triage_results', 'facts')
    op.drop_index(op.f('ix_tickets_route'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority_score'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ai_team'), table_name='tickets')
    op.drop_column('tickets', 'sla_due_at')
    op.drop_column('tickets', 'escalated')
    op.drop_column('tickets', 'route')
    op.drop_column('tickets', 'confidence')
    op.drop_column('tickets', 'priority_score')
    op.drop_column('tickets', 'ai_priority')
    op.drop_column('tickets', 'ai_team')
    op.drop_column('tickets', 'ai_service')
    op.drop_column('tickets', 'assignee')
    op.drop_table('users')
    # ### end Alembic commands ###
