"""Classify Jira work type from FinBERT text embeddings and categorical fields.

This can only be run after correcting the business entity and urgency/impact

The script trains a CatBoost gradient-boosting classifier using:
  - mean-pooled ProsusAI/finbert embeddings for Summary and Description
  - Service Team(s), Business Entity, Urgency, and Impact as categorical values

Run from the data directory with:
    python classify_work_type.py
"""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from transformers import AutoModel, AutoTokenizer


DATA_DIR = Path(__file__).resolve().parent
DEFAULT_INPUT = DATA_DIR / "jira_first_20000_requested_fields_synthetic.json"
DEFAULT_OUTPUT_DIR = DATA_DIR / "work_type_model"
DEFAULT_OUTPUT = DATA_DIR / "output" / "jira_work_type_classified.csv"
MODEL_NAME = "ProsusAI/finbert"
TEXT_COLUMNS = ("Summary", "Description")
CATEGORICAL_COLUMNS = ("Service Team(s)", "Business Entity", "Urgency", "Impact")
TARGET_COLUMN = "Work type"



def load_table(path: Path) -> pd.DataFrame:
    """Read the source dataset from either the raw JSON export or a CSV.

    The intermediate ``*_priority_mod.csv`` this used to default to was
    generated by the removed Data_Cleaning.py chain, so the raw JSON export is
    now the source of truth. Reading JSON also keeps list-valued fields as real
    lists rather than stringified ones.
    """
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    return pd.read_csv(path)


def parse_value(value: object) -> str:
    """Convert scalar and list-like CSV values to a stable categorical string."""
    if isinstance(value, (list, tuple)):
        return " | ".join(str(item) for item in value)
    if value is None or pd.isna(value):
        return "__missing__"
    text = str(value).strip()
    if text.startswith("[") and text.endswith("]"):
        try:
            parsed = ast.literal_eval(text)
        except (SyntaxError, ValueError):
            return text
        if isinstance(parsed, (list, tuple)):
            return " | ".join(str(item) for item in parsed)
    return text or "__missing__"


def embed_texts(
    texts: list[str],
    tokenizer: AutoTokenizer,
    model: AutoModel,
    device: torch.device,
    batch_size: int,
    max_length: int,
) -> np.ndarray:
    """Create mean-pooled, L2-normalized transformer embeddings."""
    embeddings: list[np.ndarray] = []
    model.eval()
    for start in range(0, len(texts), batch_size):
        batch = texts[start : start + batch_size]
        tokens = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=max_length,
            return_tensors="pt",
        )
        tokens = {name: value.to(device) for name, value in tokens.items()}
        with torch.inference_mode():
            hidden = model(**tokens).last_hidden_state
        mask = tokens["attention_mask"].unsqueeze(-1).expand(hidden.size()).float()
        pooled = (hidden * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1e-9)
        pooled = torch.nn.functional.normalize(pooled, p=2, dim=1)
        embeddings.append(pooled.cpu().numpy().astype(np.float32))
    return np.vstack(embeddings)


def build_features(
    data: pd.DataFrame,
    tokenizer: AutoTokenizer,
    model: AutoModel,
    device: torch.device,
    batch_size: int,
    max_length: int,
) -> pd.DataFrame:
    """Embed both text columns and append the requested categorical columns."""
    feature_parts: list[pd.DataFrame] = []
    for column in TEXT_COLUMNS:
        texts = data[column].fillna("").astype(str).tolist()
        vectors = embed_texts(texts, tokenizer, model, device, batch_size, max_length)
        names = [f"{column.lower()}_embedding_{index:04d}" for index in range(vectors.shape[1])]
        feature_parts.append(pd.DataFrame(vectors, columns=names, index=data.index))

    categorical = data.loc[:, CATEGORICAL_COLUMNS].copy()
    for column in CATEGORICAL_COLUMNS:
        categorical[column] = categorical[column].map(parse_value)
    return pd.concat([*feature_parts, categorical], axis=1)


def validate_columns(data: pd.DataFrame) -> None:
    required = set(TEXT_COLUMNS) | set(CATEGORICAL_COLUMNS) | {TARGET_COLUMN}
    missing = sorted(required.difference(data.columns))
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--max-length", type=int, default=256)
    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    data = load_table(args.input)
    validate_columns(data)
    data[TARGET_COLUMN] = data[TARGET_COLUMN].fillna("__missing__").astype(str)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Loading {MODEL_NAME} on {device}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModel.from_pretrained(MODEL_NAME).to(device)
    features = build_features(
        data, tokenizer, model, device, args.batch_size, args.max_length
    )

    train_indices, test_indices = train_test_split(
        np.arange(len(data)),
        test_size=args.test_size,
        random_state=args.seed,
        stratify=data[TARGET_COLUMN],
    )
    categorical_indices = [
        features.columns.get_loc(column) for column in CATEGORICAL_COLUMNS
    ]
    classifier = CatBoostClassifier(
        loss_function="MultiClass",
        iterations=500,
        depth=7,
        learning_rate=0.08,
        random_seed=args.seed,
        verbose=50,
        allow_writing_files=False,
    )
    classifier.fit(
        features.iloc[train_indices],
        data[TARGET_COLUMN].iloc[train_indices],
        cat_features=categorical_indices,
        eval_set=(features.iloc[test_indices], data[TARGET_COLUMN].iloc[test_indices]),
        early_stopping_rounds=50,
    )

    predictions = classifier.predict(features.iloc[test_indices]).ravel()
    accuracy = accuracy_score(data[TARGET_COLUMN].iloc[test_indices], predictions)
    print(f"Test accuracy: {accuracy:.4f}")
    print(classification_report(data[TARGET_COLUMN].iloc[test_indices], predictions))

    all_predictions = classifier.predict(features).ravel()
    output = data.copy()
    output[TARGET_COLUMN] = all_predictions
    args.output.parent.mkdir(parents=True, exist_ok=True)
    output.to_csv(args.output, index=False)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    classifier.save_model(args.output_dir / "work_type_catboost.cbm")
    np.savez_compressed(
        args.output_dir / "finbert_embeddings.npz",
        indices=np.arange(len(data)),
        features=features.drop(columns=list(CATEGORICAL_COLUMNS)).to_numpy(
            dtype=np.float32
        ),
    )
    metadata = {
        "embedding_model": MODEL_NAME,
        "text_columns": TEXT_COLUMNS,
        "categorical_columns": CATEGORICAL_COLUMNS,
        "target_column": TARGET_COLUMN,
        "test_accuracy": float(accuracy),
        "rows": len(data),
    }
    (args.output_dir / "metadata.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )
    print(f"Saved classified dataset to {args.output}")
    print(f"Saved model and embeddings to {args.output_dir}")


if __name__ == "__main__":
    main()
